### PR TITLE
fix(BA-7046): correct NetworkTimeoutChecker to use IdleJudgmentData

### LINKED ISSUE #13176: Manager fails to start: NetworkTimeoutChecker imports non-existent IdleJudgment
## Summary

The manager fails to start with an `ImportError` because `NetworkTimeoutChecker` imports a non-existent name `IdleJudgment` from `sokovan.idle_check.checkers.base`.

## Impact

Manager server does not boot. Fatal at startup — the import chain `server.py -> dependencies -> orchestration -> sokovan/stages/factory.py -> idle_check_judgment.py -> checkers/network_timeout.py` raises:

```
ImportError: cannot import name 'IdleJudgment' from 'ai.backend.manager.sokovan.idle_check.checkers.base'
```

## Root cause

`network_timeout.py` (added in PR #12878 / BA-6894) imports `IdleJudgment` from `checkers.base`, but that name never existed there. The actual type is `IdleJudgmentData`, defined in `ai.backend.manager.repositories.idle_checker.types` and used by the sibling `session_lifetime.py` checker and the `IdleChecker.judge` abstract contract in `base.py`. The constructor fields of the two are identical - this is purely a wrong/stale name.

The bug was merged to `main` in PR #12878 and stayed latent because `network_timeout.py` was only recently wired into the manager import graph via the sokovan stages factory; it surfaces the moment the manager actually boots.

## Fix

In `src/ai/backend/manager/sokovan/idle_check/checkers/network_timeout.py`:

- Import `IdleJudgmentData` from `ai.backend.manager.repositories.idle_checker.types` (as `session_lifetime.py` does).
- Drop `IdleJudgment` from the `checkers.base` import.
- Replace all `IdleJudgment` references (return types + constructors) with `IdleJudgmentData`.

## Verification

- `./backend.ai mgr start-server` boots cleanly.
- `./backend.ai mgr health check` -> 10/10 HEALTHY.

JIRA Issue: BA-7046

### PR DESCRIPTION
**Pull request by agatha197**
Resolves #13176 (BA-7046)

## Problem
The manager fails to boot with an `ImportError`:

```
ImportError: cannot import name 'IdleJudgment' from 'ai.backend.manager.sokovan.idle_check.checkers.base'
```

`NetworkTimeoutChecker` imports a name (`IdleJudgment`) that does not exist on `checkers.base`. It surfaces at startup via `server.py → dependencies → orchestration → sokovan/stages/factory.py → idle_check_judgment.py → checkers/network_timeout.py`.

## Root cause
The correct type is `IdleJudgmentData` (`manager.repositories.idle_checker.types`), used by the sibling `session_lifetime` checker and the `IdleChecker.judge` abstract contract in `base.py`. The two have identical constructor fields — `IdleJudgment` is simply a stale name.

This landed as a **semantic merge conflict**: the checker was authored in #12878 (BA-6894) against an earlier name, while #13108 (BA-6960) renamed the type to `IdleJudgmentData`. #12878 merged without a rebase/re-test, so the mismatch reached `main` even though each PR was green on its own branch.

## Fix
In `network_timeout.py`:
- import `IdleJudgmentData` from `repositories.idle_checker.types`
- drop `IdleJudgment` from the `checkers.base` import
- replace all `IdleJudgment` references (return types + constructors)

## Verification
- `pants fmt / fix / lint / check` — clean
- `pants test tests/unit/manager/sokovan/idle_check/test_network_timeout_checker.py` — pass
- `./backend.ai mgr start-server` boots; `./backend.ai mgr health check` → 10/10 HEALTHY

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by agatha197** [comment]
Closing as superseded. The `IdleJudgment` → `IdleJudgmentData` import fix already landed on `main` via #13148 (BA-7023, "defer idle expiration until first judgment"), which also carries additional behavioral changes on top. Merging this PR would revert those. My local checkout was 2 commits behind main, which is why the bug appeared locally.
