### PR TITLE
fix: skip resolver-backed fields in GQL from_pydantic conversion

### LINKED ISSUE #13958: ModelCardGQL.from_pydantic crashes: resolver-backed min_resource passed to __init__
## Bug

Every v2 model card GraphQL query (`adminModelCardsV2`, `scopedModelCardsV2`, node fetch, mutations returning `ModelCardV2`) fails with:

```
ModelCardGQL.__init__() got an unexpected keyword argument 'min_resource'
```

The failure is independent of the client's field selection — even `{ adminModelCardsV2(limit: 1) { edges { node { id } } } }` fails. REST v2 (`/v2/model-cards`) is unaffected.

## Root cause

Introduced in bd94f48db7 (#13708, BA-7297): `ModelCardGQL.min_resource` became an on-demand **resolver field** (reads `model_card_resource_requirements` lazily), while the `ModelCardNode` DTO (`common/dto/manager/v2/model_card/response.py`) still carries a `min_resource` field.

`_from_pydantic_kwargs()` in `manager/api/gql/pydantic_compat.py` maps every GQL dataclass field that has a same-named DTO attribute into constructor kwargs. Resolver-backed Strawberry fields are excluded from `__init__` (`field.init == False`), so passing `min_resource` raises `TypeError`.

## Fix

Skip dataclass fields with `init=False` in `_from_pydantic_kwargs()` — this fixes the whole class of bugs for any node type that pairs a DTO field with a resolver-backed GQL field.

## Repro

```bash
./bai gql '{ adminModelCardsV2(limit: 1) { count edges { node { id name } } } }'
```

### PR DESCRIPTION
**Pull request by agatha197**
## Summary
- `_from_pydantic_kwargs()` passed every same-named DTO attribute into the GQL type's generated `__init__`. Since #13708 made `ModelCardGQL.min_resource` an on-demand resolver while the `ModelCardNode` DTO still carries `min_resource` (used by REST v2), every v2 model card GQL query failed with `ModelCardGQL.__init__() got an unexpected keyword argument 'min_resource'` regardless of the client's field selection.
- Fix: a GQL type now declares the DTO fields that must stay out of constructor mapping via `__from_pydantic_exclude__`; `ModelCardGQL` excludes the resolver-backed `min_resource`. The per-type declaration is explicit — an implicit `init=False` skip could silently hide genuine field mismatches — and it also covers nested conversions (Create/Update payloads) that call `from_pydantic` recursively where call-site filtering cannot reach.
- Added a regression test.

## Test plan
- [x] `pants test tests/unit/manager/api/gql/test_pydantic_compat.py` — includes the new regression test
- [x] Pre-push `pants lint/check/test` over direct dependents passed
- [x] Verified live: `adminModelCardsV2` fails before the fix and returns data after, including `minResource`, nested `vfolder`, and `metadata` selections (the WebUI `AdminModelCardQuery` shape)

Resolves #13958

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: tests/unit/manager/api/gql/test_pydantic_compat.py [hunk 1]
```diff
@@ -200,6 +200,35 @@ def test_strawberry_definition_accessible(self) -> None:
...
+            min_resource: list[str] | None = Field(default=None, description="Lazy field")
+
+        @strawberry.type(name="LazyV2")
+        class LazyGQL(PydanticNodeMixin[Any]):
+            id: NodeID[str] = strawberry.field(description="Relay ID")
+            name: str = strawberry.field(description="Name")
+
+            @strawberry.field(description="Resolved on demand")  # type: ignore[misc]
+            async def min_resource(self) -> list[str] | None:
+                return None
```
[the remark this answers is not in the document]
Comment (agatha197) [reply tests/unit/manager/api/gql/test_pydantic_compat.py]: Replaced the decorator + suppression with a separately defined resolver passed via `strawberry.field(resolver=...)` in c4f35baa09 — the field is still `init=False` and mypy passes without the ignore.

File: tests/unit/manager/api/gql/test_pydantic_compat.py [hunk 2]
```diff
@@ -200,6 +200,35 @@ def test_strawberry_definition_accessible(self) -> None:
         assert "type" in field_names
         assert "id" in field_names
 
+    def test_resolver_backed_field_shadowing_dto_field(self) -> None:
+        """A resolver-backed GQL field whose name matches a DTO field is skipped.
+
+        Regression test: ModelCardGQL.min_resource is a resolver field while the
+        ModelCardNode DTO carries a min_resource attribute; passing it to the
+        generated __init__ raised TypeError.
```
[the remark this answers is not in the document]
Comment (agatha197) [reply tests/unit/manager/api/gql/test_pydantic_compat.py]: Condensed the docstring to three lines in c4f35baa09, keeping only the regression pointer (ModelCardGQL.min_resource vs ModelCardNode.min_resource).

**Review by HyeockJinKim — CHANGES_REQUESTED** [review]
Rather than using this approach, it would be better to handle it by actually subtracting the values from each `pydantic` object.

**Comment by agatha197** [comment]
Reworked per offline feedback: instead of implicitly skipping every `init=False` dataclass field in `_from_pydantic_kwargs`, each GQL type now explicitly declares the DTO fields to keep out of constructor mapping via `__from_pydantic_exclude__` (`ModelCardGQL` → `{"min_resource"}`). Implicit skipping could silently swallow genuine DTO/GQL field mismatches; the declaration keeps the contract visible at the type definition. It lives on the type (not call sites) so recursive conversions through Create/Update payloads are covered too.

**Comment by agatha197** [comment]
it will be handled by BA-7488
