### ISSUE TITLE
ModelCardGQL.from_pydantic crashes: resolver-backed min_resource passed to __init__

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai#13958]
## Bug

Every v2 model card GraphQL query (`adminModelCardsV2`, `scopedModelCardsV2`, node fetch, mutations returning `ModelCardV2`) fails with:

```
ModelCardGQL.__init__() got an unexpected keyword argument 'min_resource'
```

The failure is independent of the client's field selection — even `{ adminModelCardsV2(limit: 1) { edges { node { id } } } }` fails. REST v2 (`/v2/model-cards`) is unaffected.

## Root cause

Introduced in bd94f48db7 (#13708, BA-7297): `ModelCardGQL.min_resource` became an on-demand **resolver field** (reads `model_card_resource_requirements` lazily), while the `ModelCardNode` DTO (`common/dto/manager/v2/model_card/response.py`) still carries a `min_resource` field.

`_from_pydantic_kwargs()` in `manager/api/gql/pydantic_compat.py` maps every GQL dataclass field that has a same-named DTO attribute into constructor kwargs. Resolver-backed Strawberry fields are excluded from `__init__` (`field.init == False`), so passing `min_resource` raises `TypeError`.

## Fix

Skip dataclass fields with `init=False` in `_from_pydantic_kwargs()` — this fixes the whole class of bugs for any node type that pairs a DTO field with a resolver-backed GQL field.

## Repro

```bash
./bai gql '{ adminModelCardsV2(limit: 1) { count edges { node { id name } } } }'
```
